import { Algorithm, AlgorithmInfo } from "./types";

const BUBBLE_SORT_CODE = [
  'import { BarColor, FrameWithLine } from "./types";',
  "",
  "export function recordBubbleSort(input: number[]): FrameWithLine[] {",
  "  const array = [...input];",
  "  const frames: FrameWithLine[] = [];",
  "  let comparisons = 0;",
  "  let swaps = 0;",
  "",
  "  const pushFrame = (",
  "    highlights: Record<number, BarColor>,",
  "    message: string,",
  "    line?: number",
  "  ) => {",
  "    frames.push({",
  "      array: [...array],",
  "      highlights,",
  "      comparisons,",
  "      swaps,",
  "      message,",
  "      line",
  "    });",
  "  };",
  "",
  "  const markAllSorted = () => {",
  "    const sortedHighlights: Record<number, BarColor> = {};",
  "    for (let i = 0; i < array.length; i += 1) {",
  "      sortedHighlights[i] = \"sorted\";",
  "    }",
  "    return sortedHighlights;",
  "  };",
  "",
  "  pushFrame({}, \"Starting array\", 32);",
  "",
  "  for (let i = 0; i < array.length; i += 1) {",
  "    // Bubble the largest value to the end of the unsorted section.",
  "    for (let j = 0; j < array.length - i - 1; j += 1) {",
  "      comparisons += 1;",
  "      pushFrame(",
  "        { [j]: \"comparing\", [j + 1]: \"comparing\" },",
  "        `Comparing indices ${j} and ${j + 1}` ,",
  "        37",
  "      );",
  "",
  "      if (array[j] > array[j + 1]) {",
  "        swaps += 1;",
  "        [array[j], array[j + 1]] = [array[j + 1], array[j]];",
  "        pushFrame(",
  "          { [j]: \"swapping\", [j + 1]: \"swapping\" },",
  "          `Swapped indices ${j} and ${j + 1}` ,",
  "          45",
  "        );",
  "      }",
  "    }",
  "",
  "    const sortedIndex = array.length - i - 1;",
  "    pushFrame(",
  "      { [sortedIndex]: \"sorted\" },",
  "      `Index ${sortedIndex} is in final position` ,",
  "      55",
  "    );",
  "  }",
  "",
  "  pushFrame(markAllSorted(), \"Array sorted\", 63);",
  "",
  "  return frames;",
  "}"
].join("\n");

const MERGE_SORT_CODE = [
  'import { BarColor, FrameWithLine } from "./types";',
  "",
  "export function recordMergeSort(input: number[]): FrameWithLine[] {",
  "  const array = [...input];",
  "  const frames: FrameWithLine[] = [];",
  "  let comparisons = 0;",
  "  let swaps = 0;",
  "",
  "  const pushFrame = (",
  "    highlights: Record<number, BarColor>,",
  "    message: string,",
  "    line?: number",
  "  ) => {",
  "    frames.push({",
  "      array: [...array],",
  "      highlights,",
  "      comparisons,",
  "      swaps,",
  "      message,",
  "      line",
  "    });",
  "  };",
  "",
  "  const markAllSorted = () => {",
  "    const sortedHighlights: Record<number, BarColor> = {};",
  "    for (let i = 0; i < array.length; i += 1) {",
  "      sortedHighlights[i] = \"sorted\";",
  "    }",
  "    return sortedHighlights;",
  "  };",
  "",
  "  const merge = (left: number, mid: number, right: number) => {",
  "    const temp: number[] = [];",
  "    let i = left;",
  "    let j = mid + 1;",
  "",
  "    pushFrame(",
  "      { [left]: \"pivot\", [right]: \"pivot\" },",
  "      `Merging range ${left}-${right}` ,",
  "      37",
  "    );",
  "",
  "    while (i <= mid && j <= right) {",
  "      comparisons += 1;",
  "      pushFrame(",
  "        { [i]: \"comparing\", [j]: \"comparing\" },",
  "        `Comparing indices ${i} and ${j}` ,",
  "        44",
  "      );",
  "      if (array[i] <= array[j]) {",
  "        temp.push(array[i]);",
  "        i += 1;",
  "      } else {",
  "        temp.push(array[j]);",
  "        j += 1;",
  "      }",
  "    }",
  "",
  "    while (i <= mid) {",
  "      temp.push(array[i]);",
  "      i += 1;",
  "    }",
  "",
  "    while (j <= right) {",
  "      temp.push(array[j]);",
  "      j += 1;",
  "    }",
  "",
  "    for (let k = 0; k < temp.length; k += 1) {",
  "      swaps += 1;",
  "      array[left + k] = temp[k];",
  "      pushFrame(",
  "        { [left + k]: \"merging\" },",
  "        `Writing index ${left + k}` ,",
  "        70",
  "      );",
  "    }",
  "  };",
  "",
  "  const sort = (left: number, right: number) => {",
  "    if (left >= right) {",
  "      return;",
  "    }",
  "    const mid = Math.floor((left + right) / 2);",
  "    // Divide the array and merge the halves.",
  "    sort(left, mid);",
  "    sort(mid + 1, right);",
  "    merge(left, mid, right);",
  "  };",
  "",
  "  pushFrame({}, \"Starting array\", 91);",
  "  sort(0, array.length - 1);",
  "  pushFrame(markAllSorted(), \"Array sorted\", 93);",
  "",
  "  return frames;",
  "}"
].join("\n");

const QUICK_SORT_CODE = [
  'import { BarColor, FrameWithLine } from "./types";',
  "",
  "export function recordQuickSort(input: number[]): FrameWithLine[] {",
  "  const array = [...input];",
  "  const frames: FrameWithLine[] = [];",
  "  let comparisons = 0;",
  "  let swaps = 0;",
  "",
  "  const pushFrame = (",
  "    highlights: Record<number, BarColor>,",
  "    message: string,",
  "    line?: number",
  "  ) => {",
  "    frames.push({",
  "      array: [...array],",
  "      highlights,",
  "      comparisons,",
  "      swaps,",
  "      message,",
  "      line",
  "    });",
  "  };",
  "",
  "  const markAllSorted = () => {",
  "    const sortedHighlights: Record<number, BarColor> = {};",
  "    for (let i = 0; i < array.length; i += 1) {",
  "      sortedHighlights[i] = \"sorted\";",
  "    }",
  "    return sortedHighlights;",
  "  };",
  "",
  "  const partition = (low: number, high: number) => {",
  "    const pivot = array[high];",
  "    let i = low;",
  "",
  "    pushFrame(",
  "      { [high]: \"pivot\" },",
  "      `Pivot at index ${high}` ,",
  "      36",
  "    );",
  "",
  "    for (let j = low; j < high; j += 1) {",
  "      comparisons += 1;",
  "      pushFrame(",
  "        { [j]: \"comparing\", [high]: \"pivot\" },",
  "        `Comparing index ${j} to pivot` ,",
  "        43",
  "      );",
  "      if (array[j] < pivot) {",
  "        swaps += 1;",
  "        [array[i], array[j]] = [array[j], array[i]];",
  "        pushFrame(",
  "          { [i]: \"swapping\", [j]: \"swapping\" },",
  "          `Swapped indices ${i} and ${j}` ,",
  "          50",
  "        );",
  "        i += 1;",
  "      }",
  "    }",
  "",
  "    swaps += 1;",
  "    [array[i], array[high]] = [array[high], array[i]];",
  "    pushFrame(",
  "      { [i]: \"swapping\", [high]: \"swapping\" },",
  "      `Moved pivot to index ${i}` ,",
  "      61",
  "    );",
  "    pushFrame(",
  "      { [i]: \"sorted\" },",
  "      `Pivot fixed at index ${i}` ,",
  "      62",
  "    );",
  "",
  "    return i;",
  "  };",
  "",
  "  const sort = (low: number, high: number) => {",
  "    if (low >= high) {",
  "      return;",
  "    }",
  "    // Partition and recursively sort the subarrays.",
  "    const pivotIndex = partition(low, high);",
  "    sort(low, pivotIndex - 1);",
  "    sort(pivotIndex + 1, high);",
  "  };",
  "",
  "  pushFrame({}, \"Starting array\", 87);",
  "  sort(0, array.length - 1);",
  "  pushFrame(markAllSorted(), \"Array sorted\", 89);",
  "",
  "  return frames;",
  "}"
].join("\n");

export const ALGO_INFO: Record<Algorithm, AlgorithmInfo> = {
  bubble: {
    id: "bubble",
    name: "Bubble Sort",
    slug: "/bubble-sort",
    complexity: {
      best: "Ω(n)",
      average: "Θ(n²)",
      worst: "O(n²)",
      space: "O(1)"
    },
    description:
      "Bubble Sort repeatedly compares adjacent elements and swaps them when they are out of order. Each pass pushes the largest remaining value to its final position.",
    useCases:
      "Useful for teaching fundamentals, demonstrating stability, and handling very small or nearly sorted datasets where simplicity is more important than speed.",
    stable: true,
    code: BUBBLE_SORT_CODE,
    shortDescription: "Simple adjacent swaps with stable behavior."
  },
  merge: {
    id: "merge",
    name: "Merge Sort",
    slug: "/merge-sort",
    complexity: {
      best: "Ω(n log n)",
      average: "Θ(n log n)",
      worst: "O(n log n)",
      space: "O(n)"
    },
    description:
      "Merge Sort divides the array into halves, sorts each half, and merges them back together in order. It delivers consistent performance with predictable complexity.",
    useCases:
      "Great for large datasets, stable sorting requirements, and scenarios where consistent performance matters more than in-place memory usage.",
    stable: true,
    code: MERGE_SORT_CODE,
    shortDescription: "Divide, sort, and merge with consistent speed."
  },
  quick: {
    id: "quick",
    name: "Quick Sort",
    slug: "/quick-sort",
    complexity: {
      best: "Ω(n log n)",
      average: "Θ(n log n)",
      worst: "O(n²)",
      space: "O(log n)"
    },
    description:
      "Quick Sort selects a pivot, partitions elements around it, and recursively sorts each partition. Its average-case performance is fast with minimal extra memory.",
    useCases:
      "Ideal for general-purpose in-memory sorting when average speed is critical and stability is not required.",
    stable: false,
    code: QUICK_SORT_CODE,
    shortDescription: "Fast average performance with pivot partitioning."
  }
};
